---
- name: dev machine init
  hosts: localhost
  connection: local
  tasks:
    - name: upgrade system
      become: yes
      apt:
        update_cache: yes
        upgrade: dist

    - name: install necessary packages
      become: yes
      apt:
        pkg:
          - zsh
          - git
          - sshpass
          - ca-certificates
          - curl
          - apt-transport-https
          - gnupg

    - name: install or update starship
      become: yes
      shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -f

    - name: download antigen
      get_url:
        url: https://git.io/antigen
        dest: ~/antigen.zsh

    - name: get newest fzf version
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        depth: "1"

    - name: install fzf
      shell: ~/.fzf/install --completion --no-update-rc --key-bindings

    - name: create .config directory
      file:
        path: ~/.config
        state: directory

    - name: copy config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: files/home/.zshrc, dest: ~/.zshrc }
        - { src: files/home/.gitconfig, dest: ~/.gitconfig }
        - {
            src: files/home/.config/starship.toml,
            dest: ~/.config/starship.toml
          }

    - name: copy vimrc.local
      become: yes
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: files/etc/vim/vimrc.local, dest: /etc/vim/vimrc.local }

    - name: change shell to zsh
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: add golang apt repo
      become: yes
      apt_repository:
        repo: ppa:longsleep/golang-backports

    - name: add nodejs v17 repo
      become: yes
      shell: curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -

    - name: add hashicorp gpg key
      become: yes
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg

    - name: add hashicorp repo
      become: yes
      apt_repository:
        repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"

    - name: install golang, node, packer, terraform
      become: yes
      apt:
        update_cache: yes
        pkg:
          - golang-1.17
          - nodejs
          - terraform
          - packer

    - name: set go binary to version 1.17
      become: yes
      file:
        src: /usr/lib/go-1.17/bin/go
        dest: /usr/bin/go
        state: link

    - name: download gohugo deb package
      get_url:
        url: https://github.com/gohugoio/hugo/releases/download/v0.91.2/hugo_extended_0.91.2_Linux-64bit.deb
        dest: /tmp/hugo.deb

    - name: install gohugo binary
      become: yes
      apt:
        deb: /tmp/hugo.deb

    - name: remove gohugo install package
      file:
        path: /tmp/hugo.deb
        state: absent

    - name: add microsoft gpg key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: add microsoft repo
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"

    - name: install azure cli
      become: yes
      apt:
        name: azure-cli
